spring:
  application:
    name: meal-merchant
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:localhost:8848}
        enabled: ${NACOS_DISCOVERY_ENABLED:false}
server:
  port: 8102
management:
  endpoints:
    web:
      exposure:
        include: health,info
