INSERT IGNORE INTO user_account (id, phone, nickname, status, create_time, update_time)
VALUES
  (100, '13800000000', 'Demo User', 'NORMAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (101, '13800000001', 'Queue User A', 'VIP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (102, '13800000002', 'Queue User B', 'NORMAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT IGNORE INTO user_address (id, user_id, contact_name, contact_phone, detail, create_time, update_time)
VALUES
  (20, 100, 'Demo Contact', '13800000000', 'Tech Park Building 1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (21, 101, 'Queue Contact', '13800000001', 'Startup Road No.2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT IGNORE INTO merchant_employee (id, merchant_id, user_id, role_code, status, create_time, update_time)
VALUES
  (1, 10, 100, 'MERCHANT_ADMIN', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT IGNORE INTO role_permission (role_code, permission_code, create_time)
VALUES
  ('CUSTOMER', 'USER_READ', CURRENT_TIMESTAMP),
  ('CUSTOMER', 'CART_WRITE', CURRENT_TIMESTAMP),
  ('CUSTOMER', 'ORDER_WRITE', CURRENT_TIMESTAMP),
  ('CUSTOMER', 'PAYMENT_WRITE', CURRENT_TIMESTAMP),
  ('CUSTOMER', 'VOUCHER_USE', CURRENT_TIMESTAMP),
  ('CUSTOMER', 'NOTIFY_READ', CURRENT_TIMESTAMP),
  ('MERCHANT_ADMIN', 'USER_READ', CURRENT_TIMESTAMP),
  ('MERCHANT_ADMIN', 'CART_WRITE', CURRENT_TIMESTAMP),
  ('MERCHANT_ADMIN', 'ORDER_WRITE', CURRENT_TIMESTAMP),
  ('MERCHANT_ADMIN', 'PAYMENT_WRITE', CURRENT_TIMESTAMP),
  ('MERCHANT_ADMIN', 'VOUCHER_USE', CURRENT_TIMESTAMP),
  ('MERCHANT_ADMIN', 'NOTIFY_READ', CURRENT_TIMESTAMP),
  ('MERCHANT_ADMIN', 'MERCHANT_MANAGE', CURRENT_TIMESTAMP),
  ('MERCHANT_ADMIN', 'FULFILLMENT_OPERATE', CURRENT_TIMESTAMP),
  ('MERCHANT_ADMIN', 'INTERNAL_OPERATE', CURRENT_TIMESTAMP);
